name: build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          push: true
          platforms: linux/amd64      
          tags: |
            wrhsd/koodo-reader:latest
            wrhsd/koodo-reader:${{ steps.date.outputs.today }} 
